### ISSUE TITLE
Error: Call to a member function GetMediaText() on null

### ISSUE THREAD

**Issue by orat** [iobataya/dokuwiki-plugin-pubmed#1]
On my wiki the following error message ist printed:

Error: Call to a member function GetMediaText() on null
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the pubmed plugin.
More info has been written to the DokuWiki error log.

if I click on the navigation point "Kinematic models" on my docuwiki 

http://upperlimb.orat.de

The error log shows the following:

2023-08-06 21:43:18Error: Call to a member function GetMediaText() on null/homepages/43/d424136362/htdocs/upperlimb/lib/plugins/pubmed/syntax.php(113)
    #0 /homepages/43/d424136362/htdocs/upperlimb/lib/plugins/pubmed/syntax.php(43): syntax_plugin_pubmed->getSummaryXml()
    #1 /homepages/43/d424136362/htdocs/upperlimb/inc/parser/renderer.php(119): syntax_plugin_pubmed->render()
    #2 /homepages/43/d424136362/htdocs/upperlimb/inc/parserutils.php(700): Doku_Renderer->plugin()
    #3 /homepages/43/d424136362/htdocs/upperlimb/inc/parserutils.php(158): p_render()
    #4 /homepages/43/d424136362/htdocs/upperlimb/inc/parserutils.php(96): p_cached_output()
    #5 /homepages/43/d424136362/htdocs/upperlimb/inc/Ui/PageView.php(68): p_wiki_xhtml()
    #6 /homepages/43/d424136362/htdocs/upperlimb/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
    #7 /homepages/43/d424136362/htdocs/upperlimb/inc/template.php(100): dokuwiki\Action\Show->tplContent()
    #8 [internal function]: tpl_content_core()
    #9 /homepages/43/d424136362/htdocs/upperlimb/inc/Extension/Event.php(133): call_user_func_array()
    #10 /homepages/43/d424136362/htdocs/upperlimb/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
    #11 /homepages/43/d424136362/htdocs/upperlimb/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger()
    #12 /homepages/43/d424136362/htdocs/upperlimb/lib/tpl/mindthedark/main.php(63): tpl_content()
    #13 /homepages/43/d424136362/htdocs/upperlimb/inc/actions.php(27): include('/homepages/43/d...')
    #14 /homepages/43/d424136362/htdocs/upperlimb/doku.php(126): act_dispatch()
    #15 {main}

Maybe the problem is comming after upgrading the docuwiki version.

**Comment by iobataya** [comment]
Probably it was because of deprecated manner of declaration of class constructor. 

I quick-fixed those constructors in syntax.php and related classes in a sub folder. Have a try by 'Re-install' in the Extension Manager.
